# Generated by Django 5.1.15 on 2026-07-15 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrowserDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(unique=True)),
                ('platform', models.CharField(choices=[('web', 'Web')], default='web', max_length=20)),
                ('device_id', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('external_token_id', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='browser_devices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_full_name', models.CharField(db_index=True, max_length=255, verbose_name='ФИО клиента')),
                ('client_login', models.CharField(blank=True, max_length=255, verbose_name='Логин')),
                ('client_password', models.CharField(blank=True, max_length=255, verbose_name='Пароль')),
                ('exam_at', models.DateTimeField(db_index=True, verbose_name='Дата и время экзамена')),
                ('university', models.CharField(db_index=True, max_length=255, verbose_name='Вуз')),
                ('subject', models.CharField(db_index=True, max_length=255, verbose_name='Название предмета')),
                ('client_source', models.CharField(blank=True, max_length=255, verbose_name='Откуда клиент')),
                ('client_contacts', models.TextField(blank=True, verbose_name='Контакты клиента')),
                ('exam_url', models.URLField(blank=True, max_length=1000, verbose_name='Ссылка на экзамен')),
                ('custom_notify_at', models.DateTimeField(blank=True, null=True, verbose_name='Дополнительное время уведомления')),
                ('external_user_id', models.CharField(blank=True, db_index=True, max_length=80, verbose_name='ID клиента в Students Life')),
                ('external_profile_id', models.CharField(blank=True, max_length=80, verbose_name='ID профиля в Students Life')),
                ('status', models.CharField(choices=[('planned', 'Запланирован'), ('confirmed', 'Подтверждён'), ('completed', 'Завершён'), ('cancelled', 'Отменён')], default='planned', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_exams', to=settings.AUTH_USER_MODEL)),
                ('notification_recipients', models.ManyToManyField(blank=True, related_name='assigned_exams', to=settings.AUTH_USER_MODEL, verbose_name='Получатели уведомлений')),
            ],
            options={
                'ordering': ['exam_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=2000, verbose_name='Комментарий')),
                ('is_client_warned', models.BooleanField(default=False, verbose_name='Клиент предупреждён')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.exam')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ManagerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=180, verbose_name='Имя менеджера')),
                ('phone', models.CharField(blank=True, max_length=80, verbose_name='Телефон')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('day_before_08', 'За день, 08:00'), ('day_before_20', 'За день, 20:00'), ('custom', 'Дополнительное'), ('test', 'Тестовое')], max_length=30)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('sent', 'Отправлено'), ('failed', 'Ошибка'), ('skipped', 'Пропущено')], max_length=20)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='core.exam')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('exam', 'recipient', 'kind', 'scheduled_for'), name='unique_scheduled_exam_notification')],
            },
        ),
    ]
